version: 1
builder:
  configs:
    - platform: ios
      documentation_targets: [BraintreeAmericanExpress, BraintreeApplePay, BraintreeCard, BraintreeCore, BraintreeDataCollector, BraintreeLocalPayment, BraintreePayPal, BraintreePayPalNativeCheckout, BraintreeSEPADirectDebit, BraintreeThreeDSecure, BraintreeVenmo]
