name: Publish Reference Docs
description: 'Publish reference docs to GitHub Pages'
inputs:
  version:
    description: "Version of the reference docs to release"
    required: true
runs:
  using: actions/runner-images@macOS-12
  steps:
    - name: Use Xcode 14
      run: sudo xcode-select -switch /Applications/Xcode_14.0.app

    - name: Publish reference docs
      run: |
          gem install jazzy
          brew install sourcekitten

          # run sourcekitten on each Swift module individually
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme PayPalDataCollector -destination 'name=iPhone 11,platform=iOS Simulator' > pay-pal-data-collector.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreePayPalNativeCheckout -destination 'name=iPhone 11,platform=iOS Simulator' > braintree-pay-pal-native-checkout.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeSEPADirectDebit -destination 'name=iPhone 11,platform=iOS Simulator' > braintree-sepa-direct-debit.json

          # merge sourcekitten output
          jq -s '.[0] + .[1] + .[2]' pay-pal-data-collector.json braintree-pay-pal-native-checkout.json braintree-sepa-direct-debit.json > swiftDoc.json

          sourcekitten doc --objc Docs/Braintree-Umbrella-Header.h -- \
            -x objective-c -isysroot $(xcrun --show-sdk-path --sdk iphonesimulator) \
            -I $(pwd)/Sources/BraintreeAmericanExpress/Public \
            -I $(pwd)/Sources/BraintreeApplePay/Public \
            -I $(pwd)/Sources/BraintreeCard/Public \
            -I $(pwd)/Sources/BraintreeCore/Public \
            -I $(pwd)/Sources/BraintreeDataCollector/Public \
            -I $(pwd)/Sources/BraintreePaymentFlow/Public \
            -I $(pwd)/Sources/BraintreePayPal/Public \
            -I $(pwd)/Sources/BraintreeThreeDSecure/Public \
            -I $(pwd)/Sources/BraintreeUnionPay/Public \
            -I $(pwd)/Sources/BraintreeVenmo/Public \
            > objcDoc.json
          jazzy \
            --sourcekitten-sourcefile swiftDoc.json,objcDoc.json \
            --author Braintree \
            --author_url http://braintreepayments.com \
            --github_url https://github.com/braintree/braintree_ios \
            --github-file-prefix https://github.com/braintree/braintree_ios/tree/${{ inputs.version }} \
            --theme fullwidth \
            --output ${{ inputs.version }}
          git checkout gh-pages
          ln -sfn ${{ inputs.version }} current
          git add current ${{ inputs.version }}
          git commit -m "Publish ${{ inputs.version }} docs to github pages"
          git push
