#import <Foundation/Foundation.h>

/// THIS CODE IS GENERATED BY `objc_codify_certificates.swift`
/// in Braintree Github Enterprise repo `braintree-ios-certificate-generation`.
///
/// Encapsulates our trusted x509 Certificates for Secure SSL Communication with Braintree's servers
/// to avoid storing certificate files in an `NSBundle`.
///
/// Do not update this file directly. If new certificates are needed, update the `certificates` directory
/// in `braintree-ios-certificate-generation` and re-run the certificate generation script.
@interface BTAPIPinnedCertificates : NSObject

/**
 Returns the set of trusted root certificates based on the PEM files located in this directory.

 @return An array of trusted certificates encoded in the DER format, encapsulated in NSData objects.
*/
+ (NSArray *)trustedCertificates;
@end
