require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.1'

target 'ReactNativeTest' do
  use_unimodules!
  config = use_native_modules!

  pod 'Braintree', :git => 'https://github.com/braintree/braintree_ios', :branch => 'master'

  use_react_native!(:path => config["reactNativePath"])

end
