import Foundation

enum BTClientTokenError: Error, CustomNSError, LocalizedError {

    /// Authorization fingerprint was not present or invalid
    case invalidAuthorizationFingerprint

    /// Config URL was missing or invalid
    case invalidConfigURL

    /// Underlying error
    case underlyingError([String: Any])

    /// Invalid JSON
    case invalidJSON

    /// Invalid client token format
    case invalidFormat

    /// Unsupported client token version
    case unsupportedVersion

    static var errorDomain: String {
        "com.braintreepayments.BTClientTokenErrorDomain"
    }

    var errorCode: Int {
        switch self {
        case .invalidAuthorizationFingerprint:
            return 0
        case .invalidConfigURL:
            return 1
        case .underlyingError(_):
            return 2
        case .invalidJSON:
            return 3
        case .invalidFormat:
            return 4
        case .unsupportedVersion:
            return 5
        }
    }

    var errorUserInfo: [String : Any] {
        switch self {
        case .invalidAuthorizationFingerprint:
            return [
                NSLocalizedDescriptionKey: "Invalid client token. Please ensure your server is generating a valid Braintree ClientToken.",
                NSLocalizedFailureReasonErrorKey: "Authorization fingerprint was not present or invalid"
            ]

        case .invalidConfigURL:
            return [
                NSLocalizedDescriptionKey: "Invalid client token: config url was missing or invalid. Please ensure your server is generating a valid Braintree ClientToken."
            ]
            
        case .underlyingError(let error):
            return error

        case .invalidJSON:
            return [
                NSLocalizedDescriptionKey: "Invalid client token. Please ensure your server is generating a valid Braintree ClientToken.",
                NSLocalizedFailureReasonErrorKey: "Invalid JSON. Expected to find an object at JSON root."
            ]

        case .invalidFormat:
            return [
                NSLocalizedDescriptionKey: "Invalid client token format. Please pass the client token string directly as it is generated by the server-side SDK.",
                NSLocalizedFailureReasonErrorKey: "Unsupported client token format."
            ]

        case .unsupportedVersion:
            return [
                NSLocalizedDescriptionKey: "Unsupported client token version. Please ensure your server is generating a valid Braintree ClientToken with a server-side SDK that is compatible with this version of Braintree iOS.",
                NSLocalizedFailureReasonErrorKey: "Unsupported client token version."
            ]
        }
    }
}
