import Foundation

///  Error codes associated with a client token.
@objc public enum BTClientTokenError: Int, Error, CustomNSError, LocalizedError {

    /// Authorization fingerprint was not present or invalid
    case invalidAuthorizationFingerprint

    /// Config URL was missing or invalid
    case invalidConfigURL

    /// Invalid JSON
    case invalidJSON

    /// Invalid client token format
    case invalidFormat

    /// Unsupported client token version
    case unsupportedVersion

    public static var errorDomain: String {
        "com.braintreepayments.BTClientTokenErrorDomain"
    }

    public var errorCode: Int {
        rawValue
    }

    public var errorUserInfo: [String : Any] {
        switch self {
        case .invalidAuthorizationFingerprint:
            return [
                NSLocalizedDescriptionKey: "Invalid client token. Please ensure your server is generating a valid Braintree ClientToken.",
                NSLocalizedFailureReasonErrorKey: "Authorization fingerprint was not present or invalid"
            ]

        case .invalidConfigURL:
            return [
                NSLocalizedDescriptionKey: "Invalid client token: config url was missing or invalid. Please ensure your server is generating a valid Braintree ClientToken."
            ]

        case .invalidJSON:
            return [
                NSLocalizedDescriptionKey: "Invalid client token. Please ensure your server is generating a valid Braintree ClientToken.",
                NSLocalizedFailureReasonErrorKey: "Invalid JSON. Expected to find an object at JSON root."
            ]

        case .invalidFormat:
            return [
                NSLocalizedDescriptionKey: "Invalid client token format. Please pass the client token string directly as it is generated by the server-side SDK.",
                NSLocalizedFailureReasonErrorKey: "Unsupported client token format."
            ]

        case .unsupportedVersion:
            return [
                NSLocalizedDescriptionKey: "Unsupported client token version. Please ensure your server is generating a valid Braintree ClientToken with a server-side SDK that is compatible with this version of Braintree iOS.",
                NSLocalizedFailureReasonErrorKey: "Unsupported client token version."
            ]
        }
    }
}
