name: Docs
on:
  pull_request:
jobs:
  docs:
    name: Reference Docs
    runs-on: macos-15
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Xcode 16.4.0
        run: sudo xcode-select -switch /Applications/Xcode_16.4.0.app

      - name: Build reference docs
        env:
          RELEASE_VERSION: test-docs
        run: |
          set -euo pipefail
          bundle install
          brew install sourcekitten

          # run sourcekitten on each Swift module individually
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeCore -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-core.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeSEPADirectDebit -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-sepa-direct-debit.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeAmericanExpress -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-american-express.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeDataCollector -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-data-collector.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeApplePay -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-apple-pay.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeLocalPayment -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-local-payment.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeThreeDSecure -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-three-d-secure.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeCard -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-card.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreePayPal -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-paypal.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeVenmo -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-venmo.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreePayPalMessaging -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-paypal-messaging.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeShopperInsights -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-shopper-insights.json
          sourcekitten doc -- -workspace Braintree.xcworkspace -scheme BraintreeUIComponents -destination 'name=iPhone 16,platform=iOS Simulator' > braintree-ui-components.json

          # merge sourcekitten output
          jq -s '.[0] + .[1] + .[2] + .[3] + .[4] + .[5] + .[6] + .[7] + .[8] + .[9] + .[10] + .[11] + .[12]' braintree-core.json braintree-sepa-direct-debit.json braintree-american-express.json braintree-data-collector.json braintree-apple-pay.json braintree-local-payment.json braintree-three-d-secure.json braintree-card.json braintree-paypal.json braintree-venmo.json braintree-paypal-messaging.json braintree-shopper-insights.json braintree-ui-components.json > swiftDoc.json

          bundle exec jazzy \
            --sourcekitten-sourcefile swiftDoc.json \
            --author Braintree \
            --author_url http://braintreepayments.com \
            --github_url https://github.com/braintree/braintree_ios \
            --github-file-prefix "https://github.com/braintree/braintree_ios/tree/${RELEASE_VERSION}" \
            --theme fullwidth \
            --output "${RELEASE_VERSION}"
